version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v3-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install less compiler
          command: sudo npm install less@3.0.1 -g
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: v3-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run frontend tests
          command: npm run build-css && npm test

  build_image:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v3-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: v3-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build app
          command: npm run build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push docker image
          command: |
            docker build --rm=false -t "keepnetwork/website:$CIRCLE_BUILD_NUM" .
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push "keepnetwork/website:$CIRCLE_BUILD_NUM"

  slack_guardian_notification:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Notify guardian of config update if needed
          command: bash slack/notify-update.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build_image
      - slack_guardian_notification:
          filters:
            branches:
              only: master
